name: Tests

on: workflow_dispatch

permissions:
  contents: read

env:
  PYTHONUTF8: 1
  REPO_ID: bartowski/Qwen_Qwen3-0.6B-GGUF
  FILENAME: Qwen_Qwen3-0.6B-Q4_K_M.gguf
  LOCAL_DIR: model

jobs:
  download-model:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install huggingface-hub
        run: pip install huggingface-hub[hf_xet]

      - name: Create model directory (need for Windows)
        run: mkdir -p ${{ env.LOCAL_DIR }}

      - name: Cache model
        uses: actions/cache@v4
        with:
          path: ${{ env.LOCAL_DIR }}
          key: ${{ runner.os }}-model-${{ env.REPO_ID }}-${{ env.FILENAME }}
          
      - name: Download model
        run: >
          hf download ${{ env.REPO_ID }} ${{ env.FILENAME }} 
          --local-dir ${{ env.LOCAL_DIR }} --cache-dir ${{ env.LOCAL_DIR }}

  test-linux:
    needs: download-model
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Restore model cache
        uses: actions/cache@v4
        with:
          path: ${{ env.LOCAL_DIR }}
          key: ${{ runner.os }}-model-${{ env.REPO_ID }}-${{ env.FILENAME }}
      
      - name: Check model exists
        run: ls -lh ${{ env.LOCAL_DIR }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r https://github.com/sergey21000/llama-cpp-python-wheels/releases/download/v0.3.16-cpu/llama_cpp_python-0.3.16-cp312-cp312-linux_x86_64.whl
          python -m pip install -r requirements.txt

      - name: Test with pytest
        run: |
          python -m pytest -vs
